name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build for macOS
        run: make
      - name: Build for iOS
        run: make TARGET=ios
      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macOS artifacts
          path: output/macos
      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: iOS artifacts
          path: output/ios
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test macOS build
        run: make test
